services:
  php_app:
    build: .   
    ports:
      - "8000:80"
    volumes:
      - "D:/ITex/www:/var/www/html"  
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lb_pdo_netstat
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql_db

volumes:
  mysql_data: